highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "Fujie Chen Blog"
markdown: rdiscount
rdiscount:
    extensions:
      - generate_toc
      - footnotes
      - smart 
    toc_token: "@TOC"

author: "Fujie Chen"
atom-baseurl: "https://blog.fujiechen.com/"

excerpt_separator: "<!--more-->"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

#social
linkedin: "https://www.linkedin.com/in/fujiechen/"
github: "https://github.com/imaple7"


siteurl: "https://blog.fujiechen.com/"
